name: decanaria-pipeline

services:
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=jobs_project
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  # redis:
  #   image: redis:latest

  scrapy:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - postgresql
      - mongodb
      # - redis
